### ISSUE TITLE
Incorrect Malay Translation for some of the countries name

### ISSUE THREAD

**Issue by darwisabdrauf** [Hazqeel09/negara-json#1]
### Issue Description

I have observed inaccuracies in the Malay translations of certain country names within the json data.

### Examples
- "Cambodia" should be "Kemboja"
-  "Italy" should be "Itali"

###  Expected/Suggested Translation

Country names should be accurately translated into Malay, following standard conventions.

**Comment by darwisabdrauf** [comment]
@Hazqeel09, I'm interested in working on this task. Could you please assign it to me? Thanks!

**Comment by Hazqeel09** [comment]
@darwisabdrauf yes please and thank you.

**Comment by Hazqeel09** [comment]
i will close the issue because it has been fixed
